### PR TITLE
signup page created with all the Client side authentication

### PR DESCRIPTION
**Pull request by chiku011**
solved issue #5

### CODE REVIEW

**Comment by AnushkJain2201** [comment]
Please Make the following changes
1. Create an input file field for submitting DP.
2. Create an input email field.
3. Also add the check in the password field that it should contain atleast 8 words with atleast a uppercase letter and atleast a special character.

**Comment by chiku011** [comment]
ok i will work on it

**Comment by chiku011** [comment]
done please check and merge it

**Comment by JohnArryn22** [comment]
merging it. Check your Hacktoberfest Account

**Pull request merged**
